apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-todo
  template:
    metadata:
      labels:
        app: backend-todo
    spec:
      containers:
        - name: backend-todo
          image: 100xdevs/todo-app-test:1
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: env-file
            readOnly: true
            # we are mounting the .env in /secret. If we mount in the /app/ then the app will only have .env all the siurce code will erase.
            mounthPath: "/app/secret"
        volumes:
        - name: env-file
          secret:
            secretName: backend-secret
